### ISSUE TITLE
windows script host error

### ISSUE THREAD

**Issue by ethanchapp** [iwannet/LanschoolBlocker#3]
it says c:users/"my username"/ appdata/roaming/microsoft/windows/start menu/programs/startup/run.vbs
line:   1
char:   1
Error: Expected statement
Code: 800A0400
Source: microsoft VBScript compilation error

"I have tried this program on multiple computers and this keeps coming up please fix"
![Screenshot 2024-02-29 163058](https://github.com/iwannet/Projects/assets/161775134/295b9c58-c024-44c5-83e3-d55f409883c0)

**Comment by ethanchapp** [comment]
Did not work but when I go in the vbs file it says Not found

**Comment by iwannet** [comment]
Did you replace the run.vbs with the one i gave you ? And do you use windows 11 or 10 ?

**Comment by ethanchapp** [comment]
yes to both those questions

**Comment by ethanchapp** [comment]
It has code before I run the install one but after that the code disappears and turns into Not Found

**Comment by iwannet** [comment]
The  it prop means that your antivirus is blocking it, do you have any antivirus installed ?

**Comment by iwannet** [comment]
Does it work now ?

**Comment by ethanchapp** [comment]
yes, just wanted to tell you how thankful i am for you to have so much support thank you.
