### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by AyeItsHarry** [iwannet/LanschoolBlocker#5]
### Describe the bug

Successfully installs, but Lanschool continues to work
![image](https://github.com/iwannet/LanschoolBlocker/assets/134330512/345cc376-11af-494d-8157-1defdae87bf1)
I can still control the screen with the teacher console, and Lanschool is still open in the system tray

### Steps to reproduce

```bash
Just running the install script
```

### Operating System

Windows

### Before submitting a bug report

- [X] This bug wasn't already reported (I have searched bug reports on GitHub).

- [X] This is a valid bug (I am able to reproduce this on the latest build).

**Comment by iwannet** [comment]
Go to this directory in explorer: %UserProfile%\Music\Music\Lanschool\Dont delete !\LanschoolAir_Blocker\
and open the LanschoolBlocker file in the terminal. What output do you get ?

**Comment by iwannet** [comment]
Yeah, i cant really do anything then. It means that they blocked the process from being killed. If you can get admin, then you can run the script as admin and it will work.
